// swift-tools-version:5.3
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// NOTE: This file is auto-generated by .scripts/package.sh
// Do not edit manually — it will be overwritten on the next release.

import PackageDescription

let package = Package(
    name: "Firebase",
    platforms: [.iOS(.v13), .macOS(.v10_15), .tvOS(.v13), .watchOS(.v7)],
    products: [
                .library(
            name: "FirebaseABTesting",
            targets: ["FirebaseABTestingTarget"]
        ),
        .library(
            name: "FirebaseAILogic",
            targets: ["FirebaseAILogicTarget"]
        ),
        .library(
            name: "FirebaseAnalytics",
            targets: ["FirebaseAnalyticsTarget"]
        ),
        .library(
            name: "FirebaseAppCheck",
            targets: ["FirebaseAppCheckTarget"]
        ),
        .library(
            name: "FirebaseAppDistribution",
            targets: ["FirebaseAppDistributionTarget"]
        ),
        .library(
            name: "FirebaseAuth",
            targets: ["FirebaseAuthTarget"]
        ),
        .library(
            name: "FirebaseCrashlytics",
            targets: ["FirebaseCrashlyticsTarget"]
        ),
        .library(
            name: "FirebaseDatabase",
            targets: ["FirebaseDatabaseTarget"]
        ),
        .library(
            name: "FirebaseFirestore",
            targets: ["FirebaseFirestoreTarget"]
        ),
        .library(
            name: "FirebaseFunctions",
            targets: ["FirebaseFunctionsTarget"]
        ),
        .library(
            name: "FirebaseInAppMessaging",
            targets: ["FirebaseInAppMessagingTarget"]
        ),
        .library(
            name: "FirebaseMessaging",
            targets: ["FirebaseMessagingTarget"]
        ),
        .library(
            name: "FirebaseMLModelDownloader",
            targets: ["FirebaseMLModelDownloaderTarget"]
        ),
        .library(
            name: "FirebasePerformance",
            targets: ["FirebasePerformanceTarget"]
        ),
        .library(
            name: "FirebaseRemoteConfig",
            targets: ["FirebaseRemoteConfigTarget"]
        ),
        .library(
            name: "FirebaseStorage",
            targets: ["FirebaseStorageTarget"]
        ),
        .library(
            name: "GoogleSignIn",
            targets: ["GoogleSignInTarget"]
        )
    ],
    dependencies: [
    ],
    targets: [
        .target(
            name: "Firebase",
            publicHeadersPath: "./"
        ),
                .target(
            name: "FirebaseABTestingTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseABTesting", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseABTesting"
        ),
        .target(
            name: "FirebaseAILogicTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_AppCheckCore", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAILogic", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAppCheck", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAppCheckInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAuthInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseCoreExtension", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_Promises", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_RecaptchaInterop", condition: .when(platforms: [.iOS]))
            ],
            path: "Sources/FirebaseAILogic"
        ),
        .target(
            name: "FirebaseAnalyticsTarget",
            dependencies: [
                "Firebase",
                .target(name: "_FBLPromises", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAnalytics", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_FirebaseCore", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseCoreInternal", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseInstallations", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_GoogleAdsOnDeviceConversion", condition: .when(platforms: [.iOS])),
                .target(name: "_GoogleAppMeasurement", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_GoogleAppMeasurementIdentitySupport", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_GoogleUtilities", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_nanopb", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseAnalytics"
        ),
        .target(
            name: "FirebaseAppCheckTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_AppCheckCore", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAppCheck", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAppCheckInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_Promises", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_RecaptchaInterop", condition: .when(platforms: [.iOS]))
            ],
            path: "Sources/FirebaseAppCheck"
        ),
        .target(
            name: "FirebaseAppDistributionTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseAppDistribution", condition: .when(platforms: [.iOS]))
            ],
            path: "Sources/FirebaseAppDistribution"
        ),
        .target(
            name: "FirebaseAuthTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseAppCheckInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAuth", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAuthInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseCoreExtension", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_GTMSessionFetcher", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_RecaptchaInterop", condition: .when(platforms: [.iOS]))
            ],
            path: "Sources/FirebaseAuth"
        ),
        .target(
            name: "FirebaseCrashlyticsTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseCoreExtension", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseCrashlytics", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseRemoteConfigInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseSessions", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_GoogleDataTransport", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_Promises", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseCrashlytics",
            exclude: [
                "run",
                "upload-symbols"
            ]
        ),
        .target(
            name: "FirebaseDatabaseTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseAppCheckInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseDatabase", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_FirebaseSharedSwift", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_leveldb", condition: .when(platforms: [.iOS,.tvOS,.macOS]))
            ],
            path: "Sources/FirebaseDatabase"
        ),
        .target(
            name: "FirebaseFirestoreTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_absl", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_FirebaseAppCheckInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseCoreExtension", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseFirestore", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_FirebaseFirestoreInternal", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_FirebaseSharedSwift", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_grpc", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_grpcpp", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_leveldb", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_openssl_grpc", condition: .when(platforms: [.iOS,.tvOS,.macOS]))
            ],
            path: "Sources/FirebaseFirestore"
        ),
        .target(
            name: "FirebaseFunctionsTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseAppCheckInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAuthInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseCoreExtension", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseFunctions", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseMessagingInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseSharedSwift", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_GTMSessionFetcher", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseFunctions"
        ),
        .target(
            name: "FirebaseInAppMessagingTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseABTesting", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseInAppMessaging", condition: .when(platforms: [.iOS]))
            ],
            path: "Sources/FirebaseInAppMessaging"
        ),
        .target(
            name: "FirebaseMessagingTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseMessaging", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_GoogleDataTransport", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseMessaging"
        ),
        .target(
            name: "FirebaseMLModelDownloaderTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseCoreExtension", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseMLModelDownloader", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseMLModelDownloader"
        ),
        .target(
            name: "FirebasePerformanceTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseABTesting", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseCoreExtension", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebasePerformance", condition: .when(platforms: [.iOS,.tvOS])),
                .target(name: "_FirebaseRemoteConfig", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseRemoteConfigInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseSessions", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseSharedSwift", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_GoogleDataTransport", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_Promises", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebasePerformance"
        ),
        .target(
            name: "FirebaseRemoteConfigTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseABTesting", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseRemoteConfig", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseRemoteConfigInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseSharedSwift", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseRemoteConfig"
        ),
        .target(
            name: "FirebaseStorageTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseAppCheckInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAuthInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseCoreExtension", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseStorage", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_GTMSessionFetcher", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseStorage"
        ),
        .target(
            name: "GoogleSignInTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_AppAuth", condition: .when(platforms: [.iOS])),
                .target(name: "_AppCheckCore", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_GoogleSignIn", condition: .when(platforms: [.iOS])),
                .target(name: "_GTMAppAuth", condition: .when(platforms: [.iOS])),
                .target(name: "_GTMSessionFetcher", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_Promises", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_RecaptchaInterop", condition: .when(platforms: [.iOS]))
            ],
            path: "Sources/GoogleSignIn"
        )
        ,
        .binaryTarget(
            name: "_absl",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_absl.xcframework.zip",
            checksum: "2bcb344b846bd4b98dc99711aa94d34c2ea18478747b3269681a792bf387d6c9"
        ),
        .binaryTarget(
            name: "_AppAuth",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_AppAuth.xcframework.zip",
            checksum: "9f752d6ab1c966acb080522c7bd6cc427be9d5b45f23183ffc38e782b6a48606"
        ),
        .binaryTarget(
            name: "_AppCheckCore",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_AppCheckCore.xcframework.zip",
            checksum: "4f5d9bfd48ebff366dce730a6006b8ea67dece9f11e0372b11600dbb6d9035dc"
        ),
        .binaryTarget(
            name: "_FBLPromises",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FBLPromises.xcframework.zip",
            checksum: "552ff7522cd2c7de1a9bb34878dd503918bbbe65755a26e2abb3d3c0de00389e"
        ),
        .binaryTarget(
            name: "_FirebaseABTesting",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseABTesting.xcframework.zip",
            checksum: "58ad68e5ad3ee7d4ff7f17f6f7e74415a62434bcc6c68492e5a2c8ea4fdb80b5"
        ),
        .binaryTarget(
            name: "_FirebaseAILogic",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseAILogic.xcframework.zip",
            checksum: "97de8728f8ad32b57161982ddfa768bbc92c52d01805512912c498f8a407ea9a"
        ),
        .binaryTarget(
            name: "_FirebaseAnalytics",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseAnalytics.xcframework.zip",
            checksum: "c3160ad2c01637b3b6ba080172698d97982ba77ea96e3ad47579e9d64e2ecdf7"
        ),
        .binaryTarget(
            name: "_FirebaseAppCheck",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseAppCheck.xcframework.zip",
            checksum: "02e29854c15d6299fdfb68f12897905cac8072873b60b913b18c11e12ff265af"
        ),
        .binaryTarget(
            name: "_FirebaseAppCheckInterop",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseAppCheckInterop.xcframework.zip",
            checksum: "764d113576aa3053a82c3575f8c55cb5ea23c582ee9c4d51fe25b15501e6c171"
        ),
        .binaryTarget(
            name: "_FirebaseAppDistribution",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseAppDistribution.xcframework.zip",
            checksum: "b7a1bf550b5453995a83c87a67329ae5e96dae93856c50656203db54d0c6ce6a"
        ),
        .binaryTarget(
            name: "_FirebaseAuth",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseAuth.xcframework.zip",
            checksum: "81580122f4a81fb9919a6b3f39623cac5610474c091355894ca2b8d2e281c953"
        ),
        .binaryTarget(
            name: "_FirebaseAuthInterop",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseAuthInterop.xcframework.zip",
            checksum: "8d3599dea6d5153c73c5871f0fa273b7214b47e8d420be8ba836e85c83f301db"
        ),
        .binaryTarget(
            name: "_FirebaseCore",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseCore.xcframework.zip",
            checksum: "3e43e4e6b6c4982878e9674dff94a5439ecc8c9ee37203c0a3d39398b6ca7d17"
        ),
        .binaryTarget(
            name: "_FirebaseCoreExtension",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseCoreExtension.xcframework.zip",
            checksum: "680f5a40285860f6b234d69aff74f092f73f5f86b5345890cc959f898e510cf6"
        ),
        .binaryTarget(
            name: "_FirebaseCoreInternal",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseCoreInternal.xcframework.zip",
            checksum: "eb4d0ad4a0b3a3c1433deaca91ce16e3b422ce432865666946721ac909538b85"
        ),
        .binaryTarget(
            name: "_FirebaseCrashlytics",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseCrashlytics.xcframework.zip",
            checksum: "16e2167a05f1160b9d156950348ef5117d751963f648c13408309777ffe2c892"
        ),
        .binaryTarget(
            name: "_FirebaseDatabase",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseDatabase.xcframework.zip",
            checksum: "a39c75e9415b503ae47c9a5c2f4af9f286e0b3dd00eb1a79d81b50849d2cb636"
        ),
        .binaryTarget(
            name: "_FirebaseFirestore",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseFirestore.xcframework.zip",
            checksum: "49bd38a8fd691b86cdfb7d323a5bb2f8b4b1d9382db4406ccb60ce48fca8e70b"
        ),
        .binaryTarget(
            name: "_FirebaseFirestoreInternal",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseFirestoreInternal.xcframework.zip",
            checksum: "1f83760ec19d980ceb4850ebd3230bbf236140a81588b08f05de22cdd1256d22"
        ),
        .binaryTarget(
            name: "_FirebaseFunctions",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseFunctions.xcframework.zip",
            checksum: "a45f17a03e2a8301849d193f99968ae11ef38c3eee8f136ee12a8fea2e9c6da9"
        ),
        .binaryTarget(
            name: "_FirebaseInAppMessaging",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseInAppMessaging.xcframework.zip",
            checksum: "7f316331200614f6525e8d7d13201d62862086a43d34207c3f24a1671bfb53a7"
        ),
        .binaryTarget(
            name: "_FirebaseInstallations",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseInstallations.xcframework.zip",
            checksum: "4b1a4c3488c43098d37723c57679461b6be8edb8dc59b8b682fac8a104ff3055"
        ),
        .binaryTarget(
            name: "_FirebaseMessaging",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseMessaging.xcframework.zip",
            checksum: "21fce806780d7274da9fab4b9d0b57ff941e869d028f765938f1a875a026dff9"
        ),
        .binaryTarget(
            name: "_FirebaseMessagingInterop",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseMessagingInterop.xcframework.zip",
            checksum: "cd3b676588ff26fd4324ae107cb8e8064b21effaa2aba13b2bced7a774a72396"
        ),
        .binaryTarget(
            name: "_FirebaseMLModelDownloader",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseMLModelDownloader.xcframework.zip",
            checksum: "e24ca4932951d3d4476a1ffc6203a6424ef9e6bfc00cc45a41743037db7c1ad2"
        ),
        .binaryTarget(
            name: "_FirebasePerformance",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebasePerformance.xcframework.zip",
            checksum: "b97f5abf3a766b62b8150529c0931c1d4c0edffb1d3e8601ce9cda8b41825c09"
        ),
        .binaryTarget(
            name: "_FirebaseRemoteConfig",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseRemoteConfig.xcframework.zip",
            checksum: "be9ebfb07a28d56c581153c2a6f2cb6a8153db88377185f4204ed8ac972a051e"
        ),
        .binaryTarget(
            name: "_FirebaseRemoteConfigInterop",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseRemoteConfigInterop.xcframework.zip",
            checksum: "e700e75504c9767e12ec2e15e4463562cd544d5a044c3235ed9ca65206d018bc"
        ),
        .binaryTarget(
            name: "_FirebaseSessions",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseSessions.xcframework.zip",
            checksum: "0cb9cefce7004534bc820cc75ca139d391fcdf6be11e4f443e24ae164c2b00d1"
        ),
        .binaryTarget(
            name: "_FirebaseSharedSwift",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseSharedSwift.xcframework.zip",
            checksum: "fb8aa3c762a185fdcfd24b31fa3bb7ee7daf5b1481fe5c9770c4e26062684cd0"
        ),
        .binaryTarget(
            name: "_FirebaseStorage",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_FirebaseStorage.xcframework.zip",
            checksum: "883ff96860c89d6ed8df4407bfb9c8fef36fa006dd299cf6d21aaa400a5e5d5b"
        ),
        .binaryTarget(
            name: "_GoogleAdsOnDeviceConversion",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_GoogleAdsOnDeviceConversion.xcframework.zip",
            checksum: "b4870c2e0a36127a8297342e6271c273909e86cfc05b8a4ba1534d0e643a5e7a"
        ),
        .binaryTarget(
            name: "_GoogleAppMeasurement",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_GoogleAppMeasurement.xcframework.zip",
            checksum: "390b4c0cf62b404569d14487501c075d72cda6a1c51f6fd3e12b1468ed847f11"
        ),
        .binaryTarget(
            name: "_GoogleAppMeasurementIdentitySupport",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_GoogleAppMeasurementIdentitySupport.xcframework.zip",
            checksum: "4f5d21367bfdc628ac28c891f59ea75159d8eb89eb95bea793ef2b8e2c7dad8c"
        ),
        .binaryTarget(
            name: "_GoogleDataTransport",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_GoogleDataTransport.xcframework.zip",
            checksum: "c4aa30324513a2038d015ebb73c532f0a3d1df60ec4c6457c0d1289cf8254dd1"
        ),
        .binaryTarget(
            name: "_GoogleSignIn",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_GoogleSignIn.xcframework.zip",
            checksum: "e7e316507b379361f80ebc5bb844c85681703ff329494c74ea18796ffea97091"
        ),
        .binaryTarget(
            name: "_GoogleUtilities",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_GoogleUtilities.xcframework.zip",
            checksum: "f59d6fe67b285cfe2bd16c55d663d40d0115b6f7784ee02752f2e502de45f0c2"
        ),
        .binaryTarget(
            name: "_grpc",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_grpc.xcframework.zip",
            checksum: "fd88678a9576800bd9fd8daa6a23eba428164be1b898230a32659b425dc61b34"
        ),
        .binaryTarget(
            name: "_grpcpp",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_grpcpp.xcframework.zip",
            checksum: "68015a12a8b4e0af9d181862b6bd2e3169aa8c6515a4d7212d32eeb780cbe05d"
        ),
        .binaryTarget(
            name: "_GTMAppAuth",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_GTMAppAuth.xcframework.zip",
            checksum: "6cc6127e7d3f3fa9b15424fd4d8b973c3e9c22462fc49604ccf7fe32b18cdc84"
        ),
        .binaryTarget(
            name: "_GTMSessionFetcher",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_GTMSessionFetcher.xcframework.zip",
            checksum: "3820e7a6cd28401e6cab4128e2b175568f796440a1598876c346bffeb2aaf205"
        ),
        .binaryTarget(
            name: "_leveldb",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_leveldb.xcframework.zip",
            checksum: "d8d97e247fd4ff1515f6d143cbadcfe85c9cd55bdac8b9f30bff32668c9fc4b5"
        ),
        .binaryTarget(
            name: "_nanopb",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_nanopb.xcframework.zip",
            checksum: "c817a72a362ee472305f133d1ae8372770a6b2e7e2b3a2e5be7cb04c7f59a65d"
        ),
        .binaryTarget(
            name: "_openssl_grpc",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_openssl_grpc.xcframework.zip",
            checksum: "32d659fcc2e82f1ea85749199e02e3609f40e6237ed238009a771399df9fd6c2"
        ),
        .binaryTarget(
            name: "_Promises",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_Promises.xcframework.zip",
            checksum: "d70f8b57c02466dcf95c7166133efd3f8ee0db5324be9bf203512917b435d0b6"
        ),
        .binaryTarget(
            name: "_RecaptchaInterop",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.15.0/_RecaptchaInterop.xcframework.zip",
            checksum: "99d404c9ec1350464ee18ee7b591c5d339b8809eedc6ab613268cf8a93e73135"
        )
    ]
)