// swift-tools-version:5.3
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// NOTE: This file is auto-generated by .scripts/package.sh
// Do not edit manually — it will be overwritten on the next release.

import PackageDescription

let package = Package(
    name: "Firebase",
    platforms: [.iOS(.v13), .macOS(.v10_15), .tvOS(.v13), .watchOS(.v7)],
    products: [
                .library(
            name: "FirebaseABTesting",
            targets: ["FirebaseABTestingTarget"]
        ),
        .library(
            name: "FirebaseAILogic",
            targets: ["FirebaseAILogicTarget"]
        ),
        .library(
            name: "FirebaseAnalytics",
            targets: ["FirebaseAnalyticsTarget"]
        ),
        .library(
            name: "FirebaseAppCheck",
            targets: ["FirebaseAppCheckTarget"]
        ),
        .library(
            name: "FirebaseAppDistribution",
            targets: ["FirebaseAppDistributionTarget"]
        ),
        .library(
            name: "FirebaseAuth",
            targets: ["FirebaseAuthTarget"]
        ),
        .library(
            name: "FirebaseCrashlytics",
            targets: ["FirebaseCrashlyticsTarget"]
        ),
        .library(
            name: "FirebaseDatabase",
            targets: ["FirebaseDatabaseTarget"]
        ),
        .library(
            name: "FirebaseFirestore",
            targets: ["FirebaseFirestoreTarget"]
        ),
        .library(
            name: "FirebaseFunctions",
            targets: ["FirebaseFunctionsTarget"]
        ),
        .library(
            name: "FirebaseInAppMessaging",
            targets: ["FirebaseInAppMessagingTarget"]
        ),
        .library(
            name: "FirebaseMessaging",
            targets: ["FirebaseMessagingTarget"]
        ),
        .library(
            name: "FirebaseMLModelDownloader",
            targets: ["FirebaseMLModelDownloaderTarget"]
        ),
        .library(
            name: "FirebasePerformance",
            targets: ["FirebasePerformanceTarget"]
        ),
        .library(
            name: "FirebaseRemoteConfig",
            targets: ["FirebaseRemoteConfigTarget"]
        ),
        .library(
            name: "FirebaseStorage",
            targets: ["FirebaseStorageTarget"]
        ),
        .library(
            name: "GoogleSignIn",
            targets: ["GoogleSignInTarget"]
        )
    ],
    dependencies: [
    ],
    targets: [
        .target(
            name: "Firebase",
            publicHeadersPath: "./"
        ),
                .target(
            name: "FirebaseABTestingTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseABTesting", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseABTesting"
        ),
        .target(
            name: "FirebaseAILogicTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseAILogic", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAppCheckInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAuthInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseCoreExtension", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseAILogic"
        ),
        .target(
            name: "FirebaseAnalyticsTarget",
            dependencies: [
                "Firebase",
                .target(name: "_FBLPromises", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAnalytics", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_FirebaseCore", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseCoreInternal", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseInstallations", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_GoogleAdsOnDeviceConversion", condition: .when(platforms: [.iOS])),
                .target(name: "_GoogleAppMeasurement", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_GoogleAppMeasurementIdentitySupport", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_GoogleUtilities", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_nanopb", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseAnalytics"
        ),
        .target(
            name: "FirebaseAppCheckTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_AppCheckCore", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAppCheck", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAppCheckInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseAppCheck"
        ),
        .target(
            name: "FirebaseAppDistributionTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseAppDistribution", condition: .when(platforms: [.iOS]))
            ],
            path: "Sources/FirebaseAppDistribution"
        ),
        .target(
            name: "FirebaseAuthTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseAppCheckInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAuth", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAuthInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseCoreExtension", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_GTMSessionFetcher", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_RecaptchaInterop", condition: .when(platforms: [.iOS]))
            ],
            path: "Sources/FirebaseAuth"
        ),
        .target(
            name: "FirebaseCrashlyticsTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseCoreExtension", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseCrashlytics", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseRemoteConfigInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseSessions", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_GoogleDataTransport", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_Promises", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseCrashlytics",
            exclude: [
                "run",
                "upload-symbols"
            ]
        ),
        .target(
            name: "FirebaseDatabaseTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseAppCheckInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseDatabase", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_FirebaseSharedSwift", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_leveldb", condition: .when(platforms: [.iOS,.tvOS,.macOS]))
            ],
            path: "Sources/FirebaseDatabase"
        ),
        .target(
            name: "FirebaseFirestoreTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_absl", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_FirebaseAppCheckInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseCoreExtension", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseFirestore", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_FirebaseFirestoreInternal", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_FirebaseSharedSwift", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_grpc", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_grpcpp", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_leveldb", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_openssl_grpc", condition: .when(platforms: [.iOS,.tvOS,.macOS]))
            ],
            path: "Sources/FirebaseFirestore"
        ),
        .target(
            name: "FirebaseFunctionsTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseAppCheckInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAuthInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseCoreExtension", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseFunctions", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseMessagingInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseSharedSwift", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_GTMSessionFetcher", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseFunctions"
        ),
        .target(
            name: "FirebaseInAppMessagingTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseABTesting", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseInAppMessaging", condition: .when(platforms: [.iOS]))
            ],
            path: "Sources/FirebaseInAppMessaging"
        ),
        .target(
            name: "FirebaseMessagingTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseMessaging", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_GoogleDataTransport", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseMessaging"
        ),
        .target(
            name: "FirebaseMLModelDownloaderTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseCoreExtension", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseMLModelDownloader", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseMLModelDownloader"
        ),
        .target(
            name: "FirebasePerformanceTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseABTesting", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseCoreExtension", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebasePerformance", condition: .when(platforms: [.iOS,.tvOS])),
                .target(name: "_FirebaseRemoteConfig", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseRemoteConfigInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseSessions", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseSharedSwift", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_GoogleDataTransport", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_Promises", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebasePerformance"
        ),
        .target(
            name: "FirebaseRemoteConfigTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseABTesting", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseRemoteConfig", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseRemoteConfigInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseSharedSwift", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseRemoteConfig"
        ),
        .target(
            name: "FirebaseStorageTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseAppCheckInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAuthInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseCoreExtension", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseStorage", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_GTMSessionFetcher", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseStorage"
        ),
        .target(
            name: "GoogleSignInTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_AppAuth", condition: .when(platforms: [.iOS])),
                .target(name: "_AppCheckCore", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_GoogleSignIn", condition: .when(platforms: [.iOS])),
                .target(name: "_GTMAppAuth", condition: .when(platforms: [.iOS])),
                .target(name: "_GTMSessionFetcher", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/GoogleSignIn"
        )
        ,
        .binaryTarget(
            name: "_absl",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_absl.xcframework.zip",
            checksum: "ae1708fdb93d3f0f7f68da9acb5b6f95acd769537f0bb4f2fc9aeb9ede060009"
        ),
        .binaryTarget(
            name: "_AppAuth",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_AppAuth.xcframework.zip",
            checksum: "5432f232ea68ae6f10be45307f26295a078aa66bdadfd50ae286e83a126bb4da"
        ),
        .binaryTarget(
            name: "_AppCheckCore",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_AppCheckCore.xcframework.zip",
            checksum: "c2cdf726f7f117d3b57c110485669d35eb25ac3aaeba087cca84ca623e128112"
        ),
        .binaryTarget(
            name: "_FBLPromises",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FBLPromises.xcframework.zip",
            checksum: "bc813916908a61387fbeb3cb3f6db52ed32399892916e0650ce78a7dc67f7b3e"
        ),
        .binaryTarget(
            name: "_FirebaseABTesting",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseABTesting.xcframework.zip",
            checksum: "7101e92c3507e7c36ff47e29c32009fed747ef61d2296ce210aed050455eba45"
        ),
        .binaryTarget(
            name: "_FirebaseAILogic",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseAILogic.xcframework.zip",
            checksum: "0f60ddce77116765af091053c008ad7b6e3f29a47a30f19a97df62eb246e9d53"
        ),
        .binaryTarget(
            name: "_FirebaseAnalytics",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseAnalytics.xcframework.zip",
            checksum: "7f36ca3ef92a6e4c7daed8dac0ce2f6cfd040443f3c1a148d5479ba65d1c9958"
        ),
        .binaryTarget(
            name: "_FirebaseAppCheck",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseAppCheck.xcframework.zip",
            checksum: "d2111d88960d0c3c67ab5f8d654a1cf91ff7821ad58809d4b2dc25cec6dac296"
        ),
        .binaryTarget(
            name: "_FirebaseAppCheckInterop",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseAppCheckInterop.xcframework.zip",
            checksum: "7a605246d442d5ef9f3b0f4be90c452c014a9af687be758f180be5a7813bebcc"
        ),
        .binaryTarget(
            name: "_FirebaseAppDistribution",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseAppDistribution.xcframework.zip",
            checksum: "4b3753bf1c01c084abafee7b3de6a81f31300c8e01fb17977ff2d5f06e48c71a"
        ),
        .binaryTarget(
            name: "_FirebaseAuth",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseAuth.xcframework.zip",
            checksum: "adb77ce688a92968d58f2df8a4f832b860e8628165492f3f1161c7de74b646ce"
        ),
        .binaryTarget(
            name: "_FirebaseAuthInterop",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseAuthInterop.xcframework.zip",
            checksum: "e1186e899516e912ff5545332b834f8f397c91e04fe67b0ddd440ab42ca20d58"
        ),
        .binaryTarget(
            name: "_FirebaseCore",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseCore.xcframework.zip",
            checksum: "b70822ecbc8d911f6cd4267b576d22a1a1511b741bf1f83d47f70f3a019ee491"
        ),
        .binaryTarget(
            name: "_FirebaseCoreExtension",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseCoreExtension.xcframework.zip",
            checksum: "6fe1030f948eefa38a621fb0c63aeb8e109c956a064cde874fef16c5df12c900"
        ),
        .binaryTarget(
            name: "_FirebaseCoreInternal",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseCoreInternal.xcframework.zip",
            checksum: "ca0e83f52a9917567f49ab6c0b19b74bcd7a14704735415211b4a5c330cbef96"
        ),
        .binaryTarget(
            name: "_FirebaseCrashlytics",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseCrashlytics.xcframework.zip",
            checksum: "1bba90f1e33e263b88f0b95750377d8e72ba4790e36685c08439ff981d6ccc10"
        ),
        .binaryTarget(
            name: "_FirebaseDatabase",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseDatabase.xcframework.zip",
            checksum: "56fafc7255e66061002219ca033248f1f27fd80f0775873d22bb3128f8e5991c"
        ),
        .binaryTarget(
            name: "_FirebaseFirestore",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseFirestore.xcframework.zip",
            checksum: "0e974685ac53b648a3b44a52c213e9593ceb45a105d4d643e46b9d3a6c0d2f91"
        ),
        .binaryTarget(
            name: "_FirebaseFirestoreInternal",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseFirestoreInternal.xcframework.zip",
            checksum: "e08bcaf731eb694b5c9dbfda4530213fb470074605df09cdf90315b3abc4db91"
        ),
        .binaryTarget(
            name: "_FirebaseFunctions",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseFunctions.xcframework.zip",
            checksum: "04c8a5645c6fda05e5657d6f306d2a59a7c808933fe18ee46ab2e99d5631a41c"
        ),
        .binaryTarget(
            name: "_FirebaseInAppMessaging",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseInAppMessaging.xcframework.zip",
            checksum: "8b0d779c94c4a32ad36f7b7ab3f7bb97ec0537aee027777e302e1332916f44a0"
        ),
        .binaryTarget(
            name: "_FirebaseInstallations",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseInstallations.xcframework.zip",
            checksum: "ec29c5dca05e45f506024f431ac9d7df59651c1cefd39e4e8c519f7bfcf3ecc2"
        ),
        .binaryTarget(
            name: "_FirebaseMessaging",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseMessaging.xcframework.zip",
            checksum: "42820993f26465bcb38845a5a2d351e71c00b1ff5ab0e142c9bcf7f6c00ba5cf"
        ),
        .binaryTarget(
            name: "_FirebaseMessagingInterop",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseMessagingInterop.xcframework.zip",
            checksum: "9fdcc4026efb855a7eac2656eedce814df2d3dabeaa3dc2a41d1bb680fcaf668"
        ),
        .binaryTarget(
            name: "_FirebaseMLModelDownloader",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseMLModelDownloader.xcframework.zip",
            checksum: "b33d2a79824c818b09e2dc3e741bc8d4dd34b922d0ca4ba7b76ee0f7d1314917"
        ),
        .binaryTarget(
            name: "_FirebasePerformance",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebasePerformance.xcframework.zip",
            checksum: "a552d4f87b60bb687f3f57ddc12478e9b7727f50458c1d8a0e9f5d68d1eb4e20"
        ),
        .binaryTarget(
            name: "_FirebaseRemoteConfig",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseRemoteConfig.xcframework.zip",
            checksum: "d9f00af736ca20bb58226a17ba609ce796c112b4ad4a45fc291ec070197493e4"
        ),
        .binaryTarget(
            name: "_FirebaseRemoteConfigInterop",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseRemoteConfigInterop.xcframework.zip",
            checksum: "738f4619250acc2e6e79dd15bc271fdf132a3eb506ed9c6743a6e2f195d996a3"
        ),
        .binaryTarget(
            name: "_FirebaseSessions",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseSessions.xcframework.zip",
            checksum: "56cfacc8d204d5ae97dd67c4c71e9e7d07a498d97501903a0f33ffe3e62207bc"
        ),
        .binaryTarget(
            name: "_FirebaseSharedSwift",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseSharedSwift.xcframework.zip",
            checksum: "0d942738f20cd19ddbe963199d74dc6efffbd456deb0d40d68679b758fd0b85d"
        ),
        .binaryTarget(
            name: "_FirebaseStorage",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_FirebaseStorage.xcframework.zip",
            checksum: "0725f6e5c84065dcd011fb24a716aa38a0a70a7461fc1fac52be2b98290932f0"
        ),
        .binaryTarget(
            name: "_GoogleAdsOnDeviceConversion",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_GoogleAdsOnDeviceConversion.xcframework.zip",
            checksum: "619f8db9178d0acc59dab0cb8966d74291a1306360b2840370f98caca2609997"
        ),
        .binaryTarget(
            name: "_GoogleAppMeasurement",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_GoogleAppMeasurement.xcframework.zip",
            checksum: "41821ec1428b3ee297553efc28298aa96670a9f5ac7bf18bfedd2ee172083fad"
        ),
        .binaryTarget(
            name: "_GoogleAppMeasurementIdentitySupport",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_GoogleAppMeasurementIdentitySupport.xcframework.zip",
            checksum: "e9ba1e3ce1bc30fb27c56ee9d4032bc2b04ef796d54fd7768c01cecbe2f1470f"
        ),
        .binaryTarget(
            name: "_GoogleDataTransport",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_GoogleDataTransport.xcframework.zip",
            checksum: "aadde5e36fedd271f947bbe2eb4e8dafcc1ec9c8de18017ad0abdd6141766828"
        ),
        .binaryTarget(
            name: "_GoogleSignIn",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_GoogleSignIn.xcframework.zip",
            checksum: "17b9d34e076f61442e97e6eacb8f39e43695aacf9acd2e6d45cab217aaeeb5fc"
        ),
        .binaryTarget(
            name: "_GoogleUtilities",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_GoogleUtilities.xcframework.zip",
            checksum: "acc8842a474606264d1c0428f587433826903d43afdb295f875c02a23169e051"
        ),
        .binaryTarget(
            name: "_grpc",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_grpc.xcframework.zip",
            checksum: "f9b825ecd1de520784e1cee664cde005ad85862cc13796aa2f548a13d5fc088d"
        ),
        .binaryTarget(
            name: "_grpcpp",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_grpcpp.xcframework.zip",
            checksum: "f26c24dc0e0b08410c88102fcb65de2a560f57e342bbd0d6ae4d5fe8c81a7eee"
        ),
        .binaryTarget(
            name: "_GTMAppAuth",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_GTMAppAuth.xcframework.zip",
            checksum: "afbd3b4dc1a3b2fb31568cc9c3801073f6a638e810477bb37910ec886c68fe93"
        ),
        .binaryTarget(
            name: "_GTMSessionFetcher",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_GTMSessionFetcher.xcframework.zip",
            checksum: "eff591d34a50a0b8699efba732782e05b8ad735ee1ca4bd529defd66f8d45bf6"
        ),
        .binaryTarget(
            name: "_leveldb",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_leveldb.xcframework.zip",
            checksum: "61f5004d3533b5f1ed09c1ba3f86e9d1a6fd663fec4b6d1d0b5e5424363779b8"
        ),
        .binaryTarget(
            name: "_nanopb",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_nanopb.xcframework.zip",
            checksum: "ab98b3aef23e4a071831b24c4aa95ee2145b2326efaabf8f5765a5d57e42a113"
        ),
        .binaryTarget(
            name: "_openssl_grpc",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_openssl_grpc.xcframework.zip",
            checksum: "e5b848ffd8810b2524f854477e6f0f12916e88c60cd08d122004323c64c94279"
        ),
        .binaryTarget(
            name: "_Promises",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_Promises.xcframework.zip",
            checksum: "2899c34603f250a678f0c112b01ee287985de062f6820c58fee90ddff99d98ff"
        ),
        .binaryTarget(
            name: "_RecaptchaInterop",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.13.0/_RecaptchaInterop.xcframework.zip",
            checksum: "45097d55d6e84aabbaa85f82de5802d15abf39272984f8609352a7230b2b4d97"
        )
    ]
)