// swift-tools-version:5.3
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// NOTE: This file is auto-generated by .scripts/package.sh
// Do not edit manually — it will be overwritten on the next release.

import PackageDescription

let package = Package(
    name: "Firebase",
    platforms: [.iOS(.v13), .macOS(.v10_15), .tvOS(.v13), .watchOS(.v7)],
    products: [
                .library(
            name: "FirebaseABTesting",
            targets: ["FirebaseABTestingTarget"]
        ),
        .library(
            name: "FirebaseAILogic",
            targets: ["FirebaseAILogicTarget"]
        ),
        .library(
            name: "FirebaseAnalytics",
            targets: ["FirebaseAnalyticsTarget"]
        ),
        .library(
            name: "FirebaseAppCheck",
            targets: ["FirebaseAppCheckTarget"]
        ),
        .library(
            name: "FirebaseAppDistribution",
            targets: ["FirebaseAppDistributionTarget"]
        ),
        .library(
            name: "FirebaseAuth",
            targets: ["FirebaseAuthTarget"]
        ),
        .library(
            name: "FirebaseCrashlytics",
            targets: ["FirebaseCrashlyticsTarget"]
        ),
        .library(
            name: "FirebaseDatabase",
            targets: ["FirebaseDatabaseTarget"]
        ),
        .library(
            name: "FirebaseFirestore",
            targets: ["FirebaseFirestoreTarget"]
        ),
        .library(
            name: "FirebaseFunctions",
            targets: ["FirebaseFunctionsTarget"]
        ),
        .library(
            name: "FirebaseInAppMessaging",
            targets: ["FirebaseInAppMessagingTarget"]
        ),
        .library(
            name: "FirebaseMessaging",
            targets: ["FirebaseMessagingTarget"]
        ),
        .library(
            name: "FirebaseMLModelDownloader",
            targets: ["FirebaseMLModelDownloaderTarget"]
        ),
        .library(
            name: "FirebasePerformance",
            targets: ["FirebasePerformanceTarget"]
        ),
        .library(
            name: "FirebaseRemoteConfig",
            targets: ["FirebaseRemoteConfigTarget"]
        ),
        .library(
            name: "FirebaseStorage",
            targets: ["FirebaseStorageTarget"]
        ),
        .library(
            name: "GoogleSignIn",
            targets: ["GoogleSignInTarget"]
        )
    ],
    dependencies: [
    ],
    targets: [
        .target(
            name: "Firebase",
            publicHeadersPath: "./"
        ),
                .target(
            name: "FirebaseABTestingTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseABTesting", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseABTesting"
        ),
        .target(
            name: "FirebaseAILogicTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_AppCheckCore", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAILogic", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAppCheck", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAppCheckInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAuthInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseCoreExtension", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_Promises", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_RecaptchaInterop", condition: .when(platforms: [.iOS]))
            ],
            path: "Sources/FirebaseAILogic"
        ),
        .target(
            name: "FirebaseAnalyticsTarget",
            dependencies: [
                "Firebase",
                .target(name: "_FBLPromises", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAnalytics", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_FirebaseCore", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseCoreInternal", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseInstallations", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_GoogleAdsOnDeviceConversion", condition: .when(platforms: [.iOS])),
                .target(name: "_GoogleAppMeasurement", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_GoogleAppMeasurementIdentitySupport", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_GoogleUtilities", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_nanopb", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseAnalytics"
        ),
        .target(
            name: "FirebaseAppCheckTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_AppCheckCore", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAppCheck", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAppCheckInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_Promises", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_RecaptchaInterop", condition: .when(platforms: [.iOS]))
            ],
            path: "Sources/FirebaseAppCheck"
        ),
        .target(
            name: "FirebaseAppDistributionTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseAppDistribution", condition: .when(platforms: [.iOS]))
            ],
            path: "Sources/FirebaseAppDistribution"
        ),
        .target(
            name: "FirebaseAuthTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseAppCheckInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAuth", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAuthInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseCoreExtension", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_GTMSessionFetcher", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_RecaptchaInterop", condition: .when(platforms: [.iOS]))
            ],
            path: "Sources/FirebaseAuth"
        ),
        .target(
            name: "FirebaseCrashlyticsTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseCoreExtension", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseCrashlytics", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseRemoteConfigInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseSessions", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_GoogleDataTransport", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_Promises", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseCrashlytics",
            exclude: [
                "run",
                "upload-symbols"
            ]
        ),
        .target(
            name: "FirebaseDatabaseTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseAppCheckInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseDatabase", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_FirebaseSharedSwift", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_leveldb", condition: .when(platforms: [.iOS,.tvOS,.macOS]))
            ],
            path: "Sources/FirebaseDatabase"
        ),
        .target(
            name: "FirebaseFirestoreTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_absl", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_FirebaseAppCheckInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseCoreExtension", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseFirestore", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_FirebaseFirestoreInternal", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_FirebaseSharedSwift", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_grpc", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_grpcpp", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_leveldb", condition: .when(platforms: [.iOS,.tvOS,.macOS])),
                .target(name: "_openssl_grpc", condition: .when(platforms: [.iOS,.tvOS,.macOS]))
            ],
            path: "Sources/FirebaseFirestore"
        ),
        .target(
            name: "FirebaseFunctionsTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseAppCheckInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAuthInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseCoreExtension", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseFunctions", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseMessagingInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseSharedSwift", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_GTMSessionFetcher", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseFunctions"
        ),
        .target(
            name: "FirebaseInAppMessagingTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseABTesting", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseInAppMessaging", condition: .when(platforms: [.iOS]))
            ],
            path: "Sources/FirebaseInAppMessaging"
        ),
        .target(
            name: "FirebaseMessagingTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseMessaging", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_GoogleDataTransport", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseMessaging"
        ),
        .target(
            name: "FirebaseMLModelDownloaderTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseCoreExtension", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseMLModelDownloader", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseMLModelDownloader"
        ),
        .target(
            name: "FirebasePerformanceTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseABTesting", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseCoreExtension", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebasePerformance", condition: .when(platforms: [.iOS,.tvOS])),
                .target(name: "_FirebaseRemoteConfig", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseRemoteConfigInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseSessions", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseSharedSwift", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_GoogleDataTransport", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_Promises", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebasePerformance"
        ),
        .target(
            name: "FirebaseRemoteConfigTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseABTesting", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseRemoteConfig", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseRemoteConfigInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseSharedSwift", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseRemoteConfig"
        ),
        .target(
            name: "FirebaseStorageTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_FirebaseAppCheckInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseAuthInterop", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseCoreExtension", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_FirebaseStorage", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_GTMSessionFetcher", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS]))
            ],
            path: "Sources/FirebaseStorage"
        ),
        .target(
            name: "GoogleSignInTarget",
            dependencies: [
                "Firebase",
                "FirebaseAnalyticsTarget",
                .target(name: "_AppAuth", condition: .when(platforms: [.iOS])),
                .target(name: "_AppCheckCore", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_GoogleSignIn", condition: .when(platforms: [.iOS])),
                .target(name: "_GTMAppAuth", condition: .when(platforms: [.iOS])),
                .target(name: "_GTMSessionFetcher", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_Promises", condition: .when(platforms: [.iOS,.tvOS,.macOS,.watchOS])),
                .target(name: "_RecaptchaInterop", condition: .when(platforms: [.iOS]))
            ],
            path: "Sources/GoogleSignIn"
        )
        ,
        .binaryTarget(
            name: "_absl",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_absl.xcframework.zip",
            checksum: "bd518c6cbed239c16cba45ea07899c6ef323ff002ae6657fdb2bcdf205eaac41"
        ),
        .binaryTarget(
            name: "_AppAuth",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_AppAuth.xcframework.zip",
            checksum: "5ce3d422320da4689011f5559d7e0c72168f84c2b9ada54c969e9bc11a1704a5"
        ),
        .binaryTarget(
            name: "_AppCheckCore",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_AppCheckCore.xcframework.zip",
            checksum: "11f39929c06e41a669ce96baf62a65e3a26fbc4222b4a8f8fbe9bc8fe3dd1eba"
        ),
        .binaryTarget(
            name: "_FBLPromises",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FBLPromises.xcframework.zip",
            checksum: "07de48d5efaaedc2be6fb2e97d6b5774086959aa29ee513cc48e472a6563bd8c"
        ),
        .binaryTarget(
            name: "_FirebaseABTesting",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseABTesting.xcframework.zip",
            checksum: "a1104ba897c2f33ecbee55ee1bb97e9b7ae0ebb87757a339915d390254f5f986"
        ),
        .binaryTarget(
            name: "_FirebaseAILogic",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseAILogic.xcframework.zip",
            checksum: "3a1fdccf136e836c4c29ee0cb84b8dd0dad1d3b30922f8b69359f49c74d37375"
        ),
        .binaryTarget(
            name: "_FirebaseAnalytics",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseAnalytics.xcframework.zip",
            checksum: "745e3f1a8beedc545e35658dc6c887d18b52b00d06b7e47647dc0a9794d1c699"
        ),
        .binaryTarget(
            name: "_FirebaseAppCheck",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseAppCheck.xcframework.zip",
            checksum: "02121debaaee7ef3c80d686b47b77fb4500b4542f3cde015bdd335d666c7892b"
        ),
        .binaryTarget(
            name: "_FirebaseAppCheckInterop",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseAppCheckInterop.xcframework.zip",
            checksum: "86e8072998b7f548b00e009410b19f7ec2ca013f18b9ff519cd0354e40795652"
        ),
        .binaryTarget(
            name: "_FirebaseAppDistribution",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseAppDistribution.xcframework.zip",
            checksum: "1200de7402a670c6443b1c8a96988179ce3ee0dcb3590e5191b13e47635ad48d"
        ),
        .binaryTarget(
            name: "_FirebaseAuth",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseAuth.xcframework.zip",
            checksum: "415a473af9e8aec84e8a34a4617d71c20e8705f9b9d652726698de8804490a7e"
        ),
        .binaryTarget(
            name: "_FirebaseAuthInterop",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseAuthInterop.xcframework.zip",
            checksum: "18459d0c9822e943ac758d156b2c9d5b29e014802ecf776230555d383040bc8f"
        ),
        .binaryTarget(
            name: "_FirebaseCore",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseCore.xcframework.zip",
            checksum: "3014d25ee0d42c97113fea13683376b712ead0af996f6871182097e3fa36bdfb"
        ),
        .binaryTarget(
            name: "_FirebaseCoreExtension",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseCoreExtension.xcframework.zip",
            checksum: "6312fcf2827f7e463ca834da231712f6a43d613ac238af4210d99d9a257ea364"
        ),
        .binaryTarget(
            name: "_FirebaseCoreInternal",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseCoreInternal.xcframework.zip",
            checksum: "ef75ddbf159f8ae80cc6b5485d0106953e4eb007b9a483b645707bf31136b300"
        ),
        .binaryTarget(
            name: "_FirebaseCrashlytics",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseCrashlytics.xcframework.zip",
            checksum: "cc38f1779e2eafa723973ab2ad1ddf3e992caf9fca00b97a71eb02084b3a64dc"
        ),
        .binaryTarget(
            name: "_FirebaseDatabase",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseDatabase.xcframework.zip",
            checksum: "51ef0d0913acda161ab7d53c29794c448b8d4df1cd43dafea07ac8e35e80eebe"
        ),
        .binaryTarget(
            name: "_FirebaseFirestore",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseFirestore.xcframework.zip",
            checksum: "3c81e45510f1949fff5f042fc3113c7a87fe7ce7e92c25d584855842e3e8bdbe"
        ),
        .binaryTarget(
            name: "_FirebaseFirestoreInternal",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseFirestoreInternal.xcframework.zip",
            checksum: "14638d528618864fbc2f762e860f2d512ce302dc06fdc1b671329e82d6a2c610"
        ),
        .binaryTarget(
            name: "_FirebaseFunctions",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseFunctions.xcframework.zip",
            checksum: "86d6b234b969370b0e0bb59eed58a0ec7c8d3ea594a9c26011eb5cebcf85ed89"
        ),
        .binaryTarget(
            name: "_FirebaseInAppMessaging",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseInAppMessaging.xcframework.zip",
            checksum: "c5bc4ed67f9264529a70a9cffb9b5e731f04259a853bbde856b3e35309e76d60"
        ),
        .binaryTarget(
            name: "_FirebaseInstallations",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseInstallations.xcframework.zip",
            checksum: "32d56f3c345e1066b03c44afe6e5fe2ea8111b3ab6830974d94fc4240ab367f8"
        ),
        .binaryTarget(
            name: "_FirebaseMessaging",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseMessaging.xcframework.zip",
            checksum: "fbf7043fdb990508c2c64c1fb45bef24f6a53285b44ad007104be2342b5dfdd6"
        ),
        .binaryTarget(
            name: "_FirebaseMessagingInterop",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseMessagingInterop.xcframework.zip",
            checksum: "d0cfda49d6dc1410579bbb2f2bea5e0f9a9013a7c607c4744b1c7cabfff5937c"
        ),
        .binaryTarget(
            name: "_FirebaseMLModelDownloader",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseMLModelDownloader.xcframework.zip",
            checksum: "847ee841875cab93bd12193a7e621ba3d16e1bca366204db9aa90a72ce9d69e7"
        ),
        .binaryTarget(
            name: "_FirebasePerformance",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebasePerformance.xcframework.zip",
            checksum: "3e42ad84ebbe47928141cb20a814bf33a3f08b355fe26b694ce26a7524659281"
        ),
        .binaryTarget(
            name: "_FirebaseRemoteConfig",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseRemoteConfig.xcframework.zip",
            checksum: "f5d2845c787d2788b9e2cac06fc8fcb99822fc9eb1fbe3cfe8171993a1fa1cd9"
        ),
        .binaryTarget(
            name: "_FirebaseRemoteConfigInterop",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseRemoteConfigInterop.xcframework.zip",
            checksum: "26bd9d2cb30cb579f64b9c89d1ff77e97c10cbb3f5441e3f7cf65e3d1bcf0709"
        ),
        .binaryTarget(
            name: "_FirebaseSessions",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseSessions.xcframework.zip",
            checksum: "daa5976f3615c05e55c01ab15008715f12ad2fbae94afabbf23fd12b66a34863"
        ),
        .binaryTarget(
            name: "_FirebaseSharedSwift",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseSharedSwift.xcframework.zip",
            checksum: "e9de81805cf1e56119a49d0e54eeb0f2ba581ba821d4f855e6bd0506c2ac02bb"
        ),
        .binaryTarget(
            name: "_FirebaseStorage",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_FirebaseStorage.xcframework.zip",
            checksum: "326f574893d61907ecc17ec4af777dea83ce787d9fae26fdea6a8988e883505b"
        ),
        .binaryTarget(
            name: "_GoogleAdsOnDeviceConversion",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_GoogleAdsOnDeviceConversion.xcframework.zip",
            checksum: "53f5409b716b436cf0b3e01ac09d92160fe853a06786ab7aeb6f97906095492e"
        ),
        .binaryTarget(
            name: "_GoogleAppMeasurement",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_GoogleAppMeasurement.xcframework.zip",
            checksum: "ba5b88cf845dd684901e976d689ea138fd11a5e1965a95453f6a0eb2a047964f"
        ),
        .binaryTarget(
            name: "_GoogleAppMeasurementIdentitySupport",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_GoogleAppMeasurementIdentitySupport.xcframework.zip",
            checksum: "c80bb56f349a518719c3aa36b5ca60956c99e7f188b3067bf905c67014165b73"
        ),
        .binaryTarget(
            name: "_GoogleDataTransport",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_GoogleDataTransport.xcframework.zip",
            checksum: "7a7e4cb9a2bac119ab542f46e015b7f57a303bb105a54ec32d144def3fe67a70"
        ),
        .binaryTarget(
            name: "_GoogleSignIn",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_GoogleSignIn.xcframework.zip",
            checksum: "20b8dc4afe624c3894d3665b4a9b3dca1159639fea154806b4e7d7df591478f7"
        ),
        .binaryTarget(
            name: "_GoogleUtilities",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_GoogleUtilities.xcframework.zip",
            checksum: "758206ea1cec92b92ad2a0d8e181392bf13022351d1c31ddeee64e365cdff2d3"
        ),
        .binaryTarget(
            name: "_grpc",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_grpc.xcframework.zip",
            checksum: "6256d4020b2c2bf40e89b1ad2bbf197879af53074d923c76ad0a122341ca8cdb"
        ),
        .binaryTarget(
            name: "_grpcpp",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_grpcpp.xcframework.zip",
            checksum: "e616c907bac7ec3b7226344dfbb05ed9f9295ebdf3b5d12f27a17fc582f318e0"
        ),
        .binaryTarget(
            name: "_GTMAppAuth",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_GTMAppAuth.xcframework.zip",
            checksum: "980b1364a72c04f6ab25a72841a05eca89f22bfa6ded0018a133654197b92808"
        ),
        .binaryTarget(
            name: "_GTMSessionFetcher",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_GTMSessionFetcher.xcframework.zip",
            checksum: "3c104c231e2d98044a6559a94788805cce6d9f239f01f8e5647c45818d9c4c2e"
        ),
        .binaryTarget(
            name: "_leveldb",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_leveldb.xcframework.zip",
            checksum: "041eb6b4480ac399507016884e2ac41d64511ce5369d76a50300b3d0b2475865"
        ),
        .binaryTarget(
            name: "_nanopb",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_nanopb.xcframework.zip",
            checksum: "005ab905d8a85d1d1b8e3ec9a09a90828263c866087164cf7e12d726f3e9c6e7"
        ),
        .binaryTarget(
            name: "_openssl_grpc",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_openssl_grpc.xcframework.zip",
            checksum: "c33eee374c85635cec9774e4360d1c6387360d300fa4d7f6e327d705cf6be19c"
        ),
        .binaryTarget(
            name: "_Promises",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_Promises.xcframework.zip",
            checksum: "0fc0539db3a58c6a1545afa81899bc482f2fb80e18d8f2fb12b3e65b5ca12b5f"
        ),
        .binaryTarget(
            name: "_RecaptchaInterop",
            url: "https://github.com/bogdanmatasaru/firebase-ios-sdk-xcframeworks/releases/download/12.19.1/_RecaptchaInterop.xcframework.zip",
            checksum: "cb1bd8712a1716e6b02622e82949fbbd8bb8afb289206de6f55421e57c484597"
        )
    ]
)